
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Daniel M. Almonte  ## put your name
title: Mechanical Engineer Student  ## your title
location: Edison, NJ


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: https://twitter.com/almont3_danni  ## your twitter account url
linkedin: /PanelCV/assets/snapcodes/snapcode.png  ## your snapcode image url
dribbble: https://www.instagram.com/danni_almont3/  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
